config/routes.rb
Rails.application.routes.draw do
  get '/todo', to: "todos#index", as: "top"
  post '/todo/create', to: "todos#create", as: "create"
  patch '/todo/update', to: "todos#update", as: "update"
  delete '/todo/delete', to: "todos#delete", as: "delete"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todos = Todo.all()

    @new_todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html {redirect_to request.referer}
      else
        format.html {redirect_to request.referer}
      end
    end
  end

  def update
    @update_todo = Todo.find(params[:id])

    @update_todo.comment = "完了"

    respond_to do |format|
      if @update_todo.save
        format.html {redirect_to request.referer}
      else
        format.html {redirect_to request.referer}
      end
    end
  end

  def delete
    @delete_todo = Todo.find(params[:id])

    respond_to do |format|
      if @delete_todo.destroy
        format.html {redirect_to request.referer}
      else
        format.html {redirect_to request.referer}
      end
    end
  end

  private

  def todo_params
    params.require(:todo).permit(:title, :comment, :limit)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoCrud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<h1>TOPページ</h1>

<%= form_with model: @new_todo, url: create_path do |form| %>
<%= form.label :title %>
<%= form.text_field :title %>

<%= form.label :comment %>
<%= form.text_field :comment %>

<%= form.label :limit %>
<%= form.date_field :limit %>

<%= form.submit %>
<% end %>

<% @todos.each do |todo| %>
<ul>
  <li>id<%= todo.id %>のデータ</li>
  <li><%= todo.title %></li>
  <li><%= todo.comment %></li>
  <li><%= todo.limit %></li>

  <%= link_to "更新", update_path(id: todo.id), method: :patch %>
  <%= link_to "削除", delete_path(id: todo.id), method: :delete %>
</ul>

<h1>----------</h1>
<% end %>